# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "6f133d886e40665cbd8f77937c7c14dc"
name = "kunalnew"
handle = "kunalnew"
application_url = "https://speed-ca-games-mailed.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://speed-ca-games-mailed.trycloudflare.com/auth/callback",
  "https://speed-ca-games-mailed.trycloudflare.com/auth/shopify/callback",
  "https://speed-ca-games-mailed.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
